# eats-api
An Express/SocketIO-application that functions as a backend API for the Eats client (web app).

# GET /docs
+ response 200 (text/html)

# Group /polls

## Only registered users [/polls]

### Create poll [POST]

+ Parameters

  + name (string, required) - Name of the poll

  + restaurants (array, optional) - Restaurant ID's as strings to add to this poll
      + Default: []

  + users (array, optional) - User ID's as strings to add to this poll
      + Default: []

  + expires (string, optional) - Time of expiry, formatted as ISO 8601
      + Default: 20 minutes after request is received

  + allowNewRestaurants (boolean, optional) - Allow new restaurants to be added to poll after it has begun
      + Default: true

  + group (number, optional) - Group ID as string that this poll belongs to. Null for no group connection.
      + Default: null


+ Request (application/json)

{
  "name": "Name of the restaurant",
  "expires": "2017-08-07T10:46:40+00:00",
  "restaurants": ["234123","12412332"],
  "users": ["7545345", "6663523", "45656855"],
  "group": "989098098",
  "allowNewRestaurants": true
}

+ Response 200 (application/json)

{
  "data": {
    "type": "poll",
    "id": "123123123",
    "attributes": {
      "name": "Name of the restaurant",
      "expires": "2017-08-07T10:46:40Z",
      "created": "2016-02-01T15:20:05Z",
      "allow_new_restaurants": true
    }
  },
  "relationships": {
    "creator": {
      "data": {
        "type": "user",
        "id": "7545345",
      }
    },
    "restaurants": {
      "data": [{
        "type": "restaurant",
        "id": "234123",
      }, {
        "type": "restaurant",
        "id": "12412332",
      }]
    },
    "users": {
      "data": [{
        "type": "user",
        "id": "7545345",
      }, {
        "type": "user",
        "id": "6663523",
      }, {
        "type": "user",
        "id": "45656855",
      }]
    },
    "group": {
      "data": {
        "type": "group",
        "id": "45656855"
      }
    }
  },
  "links": {
    "self": "www.path.to.api/polls/123123123"
  },
  "included": [{
    "type": "restaurant",
    "id": "234123",
    "attributes": {
      "name": "Din Restaurang",
      "latitude": 56.1234,
      "longitude": 14.1234,
      "temporary": false,
    },
    "links": {
      "self": "/restaurants/234123"
    }
  }, {
    "type": "restaurant",
    "id": "12412332",
    "attributes": {
      "name": "Vår Restaurang",
      "latitude": 56.1234,
      "longitude": 14.1234,
      "temporary": false,
    },
    "links": {
      "self": "/restaurants/12412332"
    }
  }, {
    "type": "user",
    "id": "7545345",
    "attributes": {
      "name": "Per Persson",
      "photo": "https://imgur.com/erqwfdsco92.jpg",
      "anonymous": false
    },
    "links": {
      "self": "/users/7545345"
    }
  }, {
    "type": "user",
    "id": "6663523",
    "attributes": {
      "name": "Lukas Lukasson",
      "photo": "http://photo.com/1234.jpg",
      "anonymous": false
    },
    "links": {
      "self": "/users/06663523"
    }
  }, {
    "type": "user",
    "id": "45656855",
    "attributes": {
      "name": "Mats Mattsson",
      "anonymous": true
    },
    "links": {
      "self": "/users/45656855"
    }
  }, {
    "type": "group",
    "id": "45656855",
    "attributes": {
      "name": "Vi som älskar burgare på Odd Hill"
    },
    "links": {
      "self": "/groups/45656855"
    }
  }]
}
